var searchData=
[
  ['calculdamage_0',['calculDamage',['../DamageCalculator_8hpp.html#abd9a66e6dad03b9a6e1f8bad920c257f',1,'DamageCalculator.hpp']]],
  ['changestate_1',['changeState',['../classGameStateManager.html#a54870e7edea7078aa18a10b00b097231',1,'GameStateManager']]],
  ['clone_2',['clone',['../classPokemon.html#acd45fd88773e1738c89872c6cb7cd5b3',1,'Pokemon']]],
  ['createbutton_3',['createbutton',['../ElementUI_8hpp.html#a61895b931d78465bfd480d6f1af436fa',1,'createButton(const sf::Vector2f &amp;size=sf::Vector2f(0, 0), const sf::Vector2f &amp;position=sf::Vector2f(0, 0), const sf::Color &amp;buttonColor=sf::Color::Transparent, float outlineThickness=0.0f, const sf::Color &amp;outlineColor=sf::Color::Transparent, const std::string &amp;fontKey=&quot;&quot;, const std::string &amp;buttonText=&quot;&quot;, const int textSize=0, const sf::Color &amp;textColor=sf::Color::Transparent):&#160;ElementUI.cpp'],['../ElementUI_8cpp.html#a42be0d3d2016e7c410b9903c9abf5433',1,'createButton(const sf::Vector2f &amp;size, const sf::Vector2f &amp;position, const sf::Color &amp;buttonColor, float outLineThickness, const sf::Color &amp;outlineColor, const std::string &amp;fontKey, const std::string &amp;buttonText, const int textSize, const sf::Color &amp;textColor):&#160;ElementUI.cpp']]],
  ['createcircle_4',['createcircle',['../ElementUI_8hpp.html#a68564a786ba1c22261497071f480a309',1,'createCircle(float radius=0.0f, const sf::Vector2f &amp;position=sf::Vector2f(0, 0), const sf::Color &amp;fillColor=sf::Color::Transparent, float outlineThickness=0.0f, const sf::Color &amp;outlineColor=sf::Color::Transparent):&#160;ElementUI.cpp'],['../ElementUI_8cpp.html#a1d7ab43c2c3958ecfe852dccdede389e',1,'createCircle(float radius, const sf::Vector2f &amp;position, const sf::Color &amp;fillColor, float outlineThickness, const sf::Color &amp;outlineColor):&#160;ElementUI.cpp']]],
  ['createrectangle_5',['createrectangle',['../ElementUI_8hpp.html#a76d815a0e87ca0456ca15b732d4d8c50',1,'createRectangle(const sf::Vector2f &amp;size=sf::Vector2f(0, 0), const sf::Vector2f &amp;position=sf::Vector2f(0, 0), const sf::Color &amp;color=sf::Color::Transparent, float outlineThickness=0.0f, const sf::Color &amp;outlineColor=sf::Color::Transparent):&#160;ElementUI.cpp'],['../ElementUI_8cpp.html#a224ac794c376ba3d07d3b1f09202a7d7',1,'createRectangle(const sf::Vector2f &amp;size, const sf::Vector2f &amp;position, const sf::Color &amp;color, float outlineThickness, const sf::Color &amp;outlineColor):&#160;ElementUI.cpp']]],
  ['createtext_6',['createtext',['../ElementUI_8hpp.html#a6e0b235e5741e5fcb05d70dbb81ecbad',1,'createText(const std::string &amp;fontKey=&quot;&quot;, const std::string &amp;text=&quot;&quot;, unsigned int size=0, sf::Color const &amp;color=sf::Color::Transparent, sf::Vector2f const &amp;position=sf::Vector2f(0, 0)):&#160;ElementUI.cpp'],['../ElementUI_8cpp.html#aa86535bc9abc69539be8acf19452d3a3',1,'createText(const std::string &amp;fontKey, const std::string &amp;text, unsigned int charSize, const sf::Color &amp;color, const sf::Vector2f &amp;position):&#160;ElementUI.cpp']]]
];
